Issue/8
aehrc/fhir-owl pull request #13
Opened 2023-03-28 18:15 UTC by alecdorenkamp

See Issue/8.

Fixed contacts not being created properly.
Made heirarchyMeaning configurable.
Made jurisdiction configurable.
Added E2E tests to Validate that CodeSystem metadata is being represented properly.

2023-03-30 00:13 UTC, jimsteel requested changes
Some typos first

2023-03-30 00:13 UTC, jimsteel commented on src/main/java/au/csiro/fhir/owl/Application.java
> +    options.addOption("heirarchyMeaning", true, "The meaning of the hierarchy of concepts as "
```suggestion
    options.addOption("hierarchyMeaning", true, "The meaning of the hierarchy of concepts as "
```

2023-03-30 00:13 UTC, jimsteel commented on README.md
> +| -jurisdiction      | string      | Comma-separated list of jurisdictions for the codesystem. Each jurisdiction must have the format [code\|system\|display], with values retrieved from the [FHIR Jur
system|code|display might be more in keeping with FHIR's canonical syntax (which has system before code)

2023-03-30 00:13 UTC, jimsteel commented on src/test/java/au/csiro/fhir/owl/util/ArgConstants.java
> +    public static final String HEIRARCHY_MEANING_FLAG = "-heirarchyMeaning";
```suggestion
    public static final String HIERARCHY_MEANING_FLAG = "-hierarchyMeaning";
```

2023-03-30 00:13 UTC, jimsteel commented on src/test/java/au/csiro/fhir/owl/util/ArgConstants.java
> +    public static final String HEIRARCHY_MEANING_GROUPED_BY = "grouped-by"; //Static value of CodeSystem.CodeSystemHierarchyMeaning.GROUPEDBY
```suggestion
    public static final String HIERARCHY_MEANING_GROUPED_BY = "grouped-by"; //Static value of CodeSystem.CodeSystemHierarchyMeaning.GROUPEDBY
```

2023-03-30 00:13 UTC, jimsteel commented on src/test/java/au/csiro/fhir/owl/MetadataFromInputTest.java
> +import static au.csiro.fhir.owl.util.ArgConstants.HEIRARCHY_MEANING_GROUPED_BY;
```suggestion
import static au.csiro.fhir.owl.util.ArgConstants.HIERARCHY_MEANING_FLAG;
import static au.csiro.fhir.owl.util.ArgConstants.HIERARCHY_MEANING_GROUPED_BY;
```

2023-03-30 00:13 UTC, jimsteel commented on src/test/java/au/csiro/fhir/owl/MetadataFromInputTest.java
> +    HEIRARCHY_MEANING_FLAG, HEIRARCHY_MEANING_GROUPED_BY,
```suggestion
    HIERARCHY_MEANING_FLAG, HIERARCHY_MEANING_GROUPED_BY,
```

2023-03-30 00:13 UTC, jimsteel commented on README.md
> +| -heirarchyMeaning  | string      | The meaning of the hierarchy of concepts as represented in this resource. Valid values are *grouped-by*, *is-a*, *part-of*, and *classified-with*.  Default is *is
```suggestion
| -hierarchyMeaning  | string      | The meaning of the hierarchy of concepts as represented in this resource. Valid values are *grouped-by*, *is-a*, *part-of*, and *classified-with*.  Default is *is-a*. | 
```

2023-03-30 00:13 UTC, jimsteel commented on src/main/java/au/csiro/fhir/owl/FhirOwlService.java
> +      cs.setHierarchyMeaning(CodeSystem.CodeSystemHierarchyMeaning.fromCode(heirarchyMeaning));
```suggestion
    final String hierarchyMeaning = csp.getHierarchyMeaning();
    if (hierarchyMeaning != null) {
      cs.setHierarchyMeaning(CodeSystem.CodeSystemHierarchyMeaning.fromCode(hierarchyMeaning));
```

2023-03-30 00:13 UTC, jimsteel commented on src/main/java/au/csiro/fhir/owl/FhirOwlService.java
> +    // HeirarchyMeaning
```suggestion
    // HierarchyMeaning
```

2023-03-30 00:13 UTC, jimsteel commented on src/main/java/au/csiro/fhir/owl/Application.java
> +      res.setHeirarchyMeaning(val);
```suggestion
    val = line.getOptionValue("hierarchyMeaning");
    if (val != null) {
      res.setHierarchyMeaning(val);
```

2023-03-30 00:13 UTC, jimsteel commented on src/main/java/au/csiro/fhir/owl/CodeSystemProperties.java
> +  private String heirarchyMeaning = null;
```suggestion
  private String hierarchyMeaning = null;
```

2023-03-30 00:13 UTC, jimsteel commented on src/main/java/au/csiro/fhir/owl/CodeSystemProperties.java
> +    this.heirarchyMeaning = heirarchyMeaning;
```suggestion
   * Returns the hierarchyMeaning.
   *
   * @return the hierarchyMeaning
   */
  public String getHierarchyMeaning() {
    return hierarchyMeaning;
  }
  
  /**
   * Sets the hierarchyMeaning.
   *
   * @param hierarchyMeaning the hierarchyMeaning to set
   */
  public void setHierarchyMeaning(String hierarchyMeaning) {
    this.hierarchyMeaning = hierarchyMeaning;
```

2023-03-30 22:20 UTC, alecdorenkamp commented
Thanks for the feedback @jimsteel!  I believe I've made all the requested changes (hierarchy spelling and changing arg order)

2023-03-31 02:06 UTC, jimsteel approved these changes

2023-03-31 02:09 UTC, merged